title:              Tim Becker
email:              schreibstim@gmail.com
description:        Fachanwalt für IT-Recht
author:             Tim Becker
baseurl:            ""
url:                "https://becker-tim.de"

# Social Profiles
twitter_username:   ra_tbecker
github_username:    
facebook_username:  
instagram_username:  
linkedin_username: becker-tim

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
